import Link from 'next/link'
import React from 'react'

const PrivacyPolicy = () => {
    return (
        <>
            <section className=" __mainContainer pt-[50px] pb-[80px] lg:pt-[150px] lg:pb-[150px] relative z-[1]">
                <div className="max-w-[1055px] lg:max-w-[980px] xl:max-w-[1055px] w-full mx-auto relative">
                    <h4 className="__ldHead text-center">Privacy Policy</h4>

                    <p className="text-base lg:text-lg mb-4">Last updated: 9th March 2025</p>

                    <p className="text-base lg:text-lg mb-4">This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information, collected (as disclosed) by you, when you use our website, application and its service(s), and informs you about your privacy rights and how the law protects you.</p>

                    <p className="text-base lg:text-lg mb-4">We use your Personal data collected by us, to provide and improve your service experience with us. By using our website, application and its service(s), you agree to the collection and use of information in accordance with this Privacy Policy.</p>

                    <p className="text-lg lg:text-[20px] mb-1"><b className=' font-semibold'>Interpretation and Definitions</b></p>
                    
                    <p className="text-base lg:text-lg mb-4"><b className=' font-semibold'>Interpretation :</b> The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                    <p className="text-base lg:text-lg mb-4"><b className=' font-semibold'>Definitions :</b> For the purposes of this Privacy Policy:</p>
                    
                    <ul className=' list-disc pl-[25px]'>
                        <li className="text-base lg:text-lg mb-4">Application refers to the Website, application “mysifarish” as available on Internet, Android Play Store and iOS App Store.</li>
                        <li className="text-base lg:text-lg mb-4">Account means a unique account created for you to access our Service or parts of our Service, on our Website and/or application.</li>
                        <li className="text-base lg:text-lg mb-4">Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Solresol  Technologies Pvt Ltd  who legally owns the product mysifarish.</li>
                        <li className="text-base lg:text-lg mb-4">Cookies are small files that are placed on your computer, mobile device or any other device by a website and/or Application, containing the details of your browsing history on that website and/or application among its many uses.</li>
                        <li className="text-base lg:text-lg mb-4">Country refers to: India</li>
                        <li className="text-base lg:text-lg mb-4">Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                        <li className="text-base lg:text-lg mb-4">Personal Data is any information that relates to an identified or identifiable individual, but does not include Passwords and related Confidential Information.</li>
                        <li className="text-base lg:text-lg mb-4">Service refers to  the Website (“mysifarish.com”) and/or the application “mysifarish.com” including its pages and links.</li><li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analysing how the Service is used.</li>
                        <li className="text-base lg:text-lg mb-4">Third-party Social Media Service refers to any website/ application or any social network website/ application through which a User can log in or create an account to use the Service.</li>
                        <li className="text-base lg:text-lg mb-4">Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                        <li className="text-base lg:text-lg mb-4">Website refers the web page www.mysifarish.com</li>
                        <li className="text-base lg:text-lg mb-4">You mean the individual accessing or using the Service, or the company, or other individual or legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                    </ul>

                    <p className="text-base lg:text-lg mb-4"><b className=' font-semibold'>Collecting and Using Your Personal Data</b></p>

                    <p className="text-lg lg:text-[20px] mb-1 "><b className=' font-semibold'>Types of Data Collected </b> </p>

                    <p className="text-base lg:text-lg mb-4"><b className=' font-semibold'>Personal Data</b></p>
                    <p className="text-base lg:text-lg mb-4">While using our Service, We may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>

                    <ul className=' list-disc pl-[25px]'>
                        <li className="text-base lg:text-lg mb-4">Email address</li>
                        <li className="text-base lg:text-lg mb-4">First name and last name</li>
                        <li className="text-base lg:text-lg mb-4">Phone number</li>
                        <li className="text-base lg:text-lg mb-4">Address, State, Province, ZIP/Postal code, City</li>
                        <li className="text-base lg:text-lg mb-4">Generation details</li>
                        <li className="text-base lg:text-lg mb-4">Phone Contacts</li>
                        <li className="text-base lg:text-lg mb-4">GPS Locations</li>
                    </ul>

                    <p className="text-lg lg:text-[20px] mb-1 "><b className=' font-semibold'>Usage Data</b> </p>

                    <p className="text-base lg:text-lg mb-4">Usage Data is collected automatically when using the Service.</p>
                    <p className="text-base lg:text-lg mb-4">Usage Data may include information such as your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p className="text-base lg:text-lg mb-4">When you access the Service through any device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your device’s unique ID, the IP address of your device, your device’s operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.</p>
                    <p className="text-base lg:text-lg mb-4">We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through any device.</p>
                    <p className="text-base lg:text-lg mb-4">Information from Third-Party Social Media Services</p>

                    <p className="text-lg lg:text-[20px] mb-1 "><b className=' font-semibold'>The Company may  allow you to create an account and log in to use the Service through the following Third-party Social Media Services:</b> </p>

                    <ul className=' list-disc pl-[25px]'>
                        <li className="text-base lg:text-lg mb-4">Google</li>
                        <li className="text-base lg:text-lg mb-4">Facebook</li>
                        <li className="text-base lg:text-lg mb-4">Instagram</li>
                        <li className="text-base lg:text-lg mb-4">Twitter</li>
                    </ul>

                    <p className="text-base lg:text-lg mb-4">If you decide to register through or otherwise grant us access to a Third-Party Social Media Service, we may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as your name, your email address, your activities or your contact list associated with that account.</p>

                    <p className="text-base lg:text-lg mb-4">You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If you choose to provide such information and Personal Data, during registration or otherwise, you are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>

                    <p className="text-lg lg:text-[20px] mb-1 "><b className=' font-semibold'>Tracking Technologies and Cookies</b> </p>
                    <p className="text-base lg:text-lg mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyse our Service. The technologies we use may include:</p>

                    <ul className=' list-disc pl-[25px]'>
                        <li className="text-base lg:text-lg mb-4">Cookies or Browser Cookies. A cookie is a small file placed on your Device. You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of our Service. Unless you have adjusted your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                        <li className="text-base lg:text-lg mb-4">Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about your preferences or your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how you can delete Flash Cookies, please read "Where can I change the settings for disabling, or deleting local shared objects?" available at https://helpx.adobe.com/flash-player/kb/disable-local-sharedobjectsflash. html#main.Where_can_I_change_the_settings_for_disabling__or_deleting_local_share objects_</li>
                        <li className="text-base lg:text-lg mb-4">Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website/application statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                    </ul>

                    <p className="text-base lg:text-lg mb-4">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when you go offline, while Session Cookies are deleted as soon as you close your web browser. Learn more about cookies: Cookies: What Do They Do?.</p>

                    <p className="text-base lg:text-lg mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>

                    <ul className=' list-disc pl-[25px]'>
                        <li className="text-base lg:text-lg mb-4">Necessary / Essential Cookies <br /> Type: Session Cookies <br /> Administered by: Us <br />Purpose: These Cookies are essential to provide you with services available through the Website/application and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that you have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>

                        <li className="text-base lg:text-lg mb-4">Cookies Policy / Notice Acceptance Cookies <br />Type: Persistent Cookies <br />Administered by: Us <br />Purpose: These Cookies identify if users have accepted the use of cookies on the Website/ application.</li>

                        <li className="text-base lg:text-lg mb-4">Functionality Cookies <br />Type: Persistent Cookies <br /> Administered by: Us <br />Purpose: These Cookies allow us to remember choices you make when you use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide you with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website/application.</li>
                    </ul>
                    
                    <p className="text-lg lg:text-[20px] mb-1 "><b className=' font-semibold'>For more information about the cookies we use and your choices regarding cookies, pleasevisit our Cookies Policy or the Cookies section of our Privacy Policy.</b> </p>
                    <p className="text-lg lg:text-[20px] mb-1">Use of Your Personal Data</p>
                    <p className="text-base lg:text-lg mb-4">The Company may use Personal Data for the following purposes:</p>

                    <ul className=' list-disc pl-[25px]'>
                        <li className="text-base lg:text-lg mb-4">To provide and maintain our Service, including to monitor the usage of our Service.</li>

                        <li className="text-base lg:text-lg mb-4">To provide and maintain our Service, including to monitor the usage of our Service.</li>

                        <li className="text-base lg:text-lg mb-4">To manage your Account: to manage your registration as a user of the Service. The Personal Data you provide can give you access to different functionalities of the Service that are available to you as a registered user.</li>

                        <li className="text-base lg:text-lg mb-4">For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services you have purchased or of any other contract with us through the Service.</li>

                        <li className="text-base lg:text-lg mb-4">To contact you: To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>

                        <li className="text-base lg:text-lg mb-4">To provide you with recommendations, news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.</li>

                        <li className="text-base lg:text-lg mb-4">To manage your requests: To attend and manage your requests to us.</li>

                        <li className="text-base lg:text-lg mb-4">For other purposes: We may use your information for other purposes, such as data analysis, profiling you as per your interactions with the app, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, marketing and your experience.</li>
                    </ul>

                    <p className="text-base lg:text-lg mb-4">We may share your personal information in the following situations:</p>

                    <ul className=' list-disc pl-[25px]'>
                        <li className="text-base lg:text-lg mb-4">With Service Providers: We may share your personal information with Service Providers to monitor and analyse the use of our Service, to contact you.</li>

                        <li className="text-base lg:text-lg mb-4">With Affiliates: We may share your information with our affiliates, in which case we will require those affiliates to honour this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners or other companies that we control or that are under common control with us.</li>

                        <li className="text-base lg:text-lg mb-4">With business partners: We may share your information with our business partners to offer you certain products, services or promotions.</li>

                        <li className="text-base lg:text-lg mb-4">With other users: when you share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If you interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see your name, profile, pictures and description of your activity. Similarly, other users will be able to view descriptions of your activity, communicate with You and view Your profile.</li>

                        <li className="text-base lg:text-lg mb-4">With Your consent: We may disclose your personal information for any other purpose with your consent.
                        Retention of Your Personal Data</li>
                    </ul>

                    <p className="text-base lg:text-lg mb-4">Retention of Your Personal Data</p>

                    <p className="text-base lg:text-lg mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

                    <p className="text-base lg:text-lg mb-4">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or we are legally obligated to retain this data for longer time periods.</p>

                    <p className="text-lg lg:text-[20px] mb-1 ">Transfer of Your Personal Data</p>
                    <p className="text-base lg:text-lg mb-4">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>


                    <p className="text-base lg:text-lg mb-4">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>

                    <p className="text-base lg:text-lg mb-4">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

                    <p className="text-lg lg:text-[20px] mb-1 ">Disclosure of Your Personal Data</p>

                    <p className="text-base lg:text-lg mb-4">Business Transactions</p>
                    <p className="text-base lg:text-lg mb-4">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

                    <p className="text-base lg:text-lg mb-4">Law enforcement</p>

                    <p className="text-base lg:text-lg mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

                    <p className="text-base lg:text-lg mb-4">Other legal requirements</p>

                    <p className="text-base lg:text-lg mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>

                    <ul className=' list-disc pl-[25px]'>
                        <li className="text-base lg:text-lg mb-4">Comply with a legal obligation</li>

                        <li className="text-base lg:text-lg mb-4">Protect and defend the rights or property of the Company</li>

                        <li className="text-base lg:text-lg mb-4">Prevent or investigate possible wrongdoing in connection with the Service</li>

                        <li className="text-base lg:text-lg mb-4">Protect the personal safety of Users of the Service or the public</li>

                        <li className="text-base lg:text-lg mb-4">Protect against legal liability</li>
                    </ul>

                    <p className="text-lg lg:text-[20px] mb-1 ">Security of Your Personal Data</p>
                    <p className="text-base lg:text-lg mb-4">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

                    <p className="text-lg lg:text-[20px] mb-1 ">Children's Privacy</p>

                    <p className="text-base lg:text-lg mb-4">Our Service does not address anyone under the age of 18, directly. We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided Us with Personal Data, please contact Us. If we become aware that we have collected Personal Data from anyone under the age of 18 without verification of parental consent, We take steps to remove that information from Our servers.</p>

                    <p className="text-base lg:text-lg mb-4">If we need to rely on consent as a legal basis for processing your information, we may require your parent's consent before we collect and use that information.</p>

                    <p className="text-base lg:text-lg mb-4">Links to Other Websites/Applications</p>

                    <p className="text-base lg:text-lg mb-4">Our Service may contain links to other websites/applications that are not operated by us. If You click on a third-party link, you will be directed to that third party's site/application. We strongly advise you to review the Privacy Policy of every site/app you visit.</p>

                    <p className="text-base lg:text-lg mb-4">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites, applications or services.</p>

                    <p className="text-base lg:text-lg mb-4">Changes to this Privacy Policy</p>

                    <p className="text-base lg:text-lg mb-4">We may update Our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

                    <p className="text-base lg:text-lg mb-4">We will let you know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>

                    <p className="text-base lg:text-lg mb-4">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

                    <p className="text-lg lg:text-[20px] mb-1 ">Contact Us</p>

                    <p className="text-base lg:text-lg mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>

                    <ul className=' list-disc pl-[25px]'>
                        <li>By email: <Link href="contact@solresoltechnologies.com">contact@solresoltechnologies.com</Link></li>
                    </ul>

                    <p className="text-base lg:text-lg ">© Privacy Policy for Solresol Technologies Pvt Ltd.</p>
                </div>
            </section>
        </>
    )
}

export default PrivacyPolicy